trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/pipelines.yaml
    - terraform/*

variables:
  working_directory: './terraform'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: Download Code
  clean: true
  fetchDepth: 5
  lfs: true

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Init'
  inputs:
    workingDirectory: terraform
    backendServiceArm: MyAzureConnection
    backendAzureRmResourceGroupName: 'cdw-iacutils-resources'
    backendAzureRmStorageAccountName: cdwterraformstate
    backendAzureRmContainerName: learnazfunc
    backendAzureRmKey: state.tfstate

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Plan'
  inputs:
    command: plan
    workingDirectory: terraform
    commandOptions: '-out=out.tfplan -var="resource_name=$(resource_name)" -var="location=$(location)"'
    environmentServiceNameAzureRM: MyAzureConnection

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform Apply'
  inputs:
    command: apply
    workingDirectory: terraform
    commandOptions: 'out.tfplan'
    environmentServiceNameAzureRM: MyAzureConnection