trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/pipelines.yaml
    - terraform/*

variables:
  working_directory: './terraform'
  name: 'cdw-myresourcegroup-test'
  location: 'westus2'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: Download Code
  clean: true
  fetchDepth: 5
  lfs: true
  #path: terraformplan

- download: current
  displayName: Download Plan
  artifact: terraformplan

- task: AzureCLI@2
  displayName: Terraform Apply
  inputs:
    azureSubscription: $(service_connection_name)
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    workingDirectory: $(working_directory)
    inlineScript: |
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_SUBSCRIPTION_ID=$(az account show -o json | jq -r '.id')
      export ARM_TENANT_ID=$(az account show -o json | jq -r '.tenantId')
      
      terraform init \
        -backend-config="storage_account_name=$(tfstate_storage_account_name)" \
        -backend-config="container_name=$(tfstate_container_name)" \
        -backend-config="key=$(tfstate_key)" \
        -backend-config="access_key=$(tfstate_access_key)"

      terraform plan \
        -out=out.tfplan \
        -var='name=$(resource_name)' \
        -var='location=$(location)'
      
      terraform apply out.tfplan